# Generated by Django 5.1.5 on 2025-08-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="content",
            field=models.TextField(default=""),
        ),
    ]
