# Generated by Django 5.1.5 on 2025-08-06 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_notes_content"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notes",
            new_name="Note",
        ),
    ]
